#1348 doc preview only for PR for master
pytorch/ignite pull request #1350
Opened 2020-10-04 04:35 UTC by sroy8091

Fixes #1348

Description:
update of travis for doc preview

Check list:
* [ ] Documentation is updated (if required)

2020-10-04 12:15 UTC, vfdev-5 reviewed
Thanks for the PR !
Could you also add ["Nice to have"](https://github.com/pytorch/ignite/issues/1270#issuecomment-703180980) features ?

2020-10-04 12:15 UTC, vfdev-5 commented on .travis.yml
> +      if: type != cron AND branch = master
I'm not sure if this worked. See current travis CI report where we still build the docs.

2020-10-05 09:55 UTC, sroy8091 commented
@vfdev-5 as you can see the travis build it doesn't have doc build so only if pr base branch is master it will create. Is there a different behaviour you are expecting?

2020-10-05 10:02 UTC, vfdev-5 commented
Thanks @sroy8091 ! Probably, I was not enough clear about the intention. We would like to have the following behaviour:
- if build is a PR, we do not build the docs as netlify will do it and show a preview.
- if it is a merged PR and we rebuild the master, then we build and deploy the docs as previously.

2020-10-07 20:19 UTC, vfdev-5 commented
@sroy8091 any updates on this PR ? Let me know if you get stuck at some point such that we could help.

2020-10-08 11:16 UTC, sroy8091 commented
@vfdev-5 yes i tried different things but it seems to not working. Does this seems workable https://stackoverflow.com/questions/12878568/travis-ci-triggers-build-only-for-master-branch-in-github-repo?

2020-10-08 19:43 UTC, vfdev-5 commented
@sroy8091 can you check travis docs : https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
and see if we can use `TRAVIS_PULL_REQUEST` as a condition.

That's correct that `branch: onlyl` specifies PR targeting a branch

> To only build pull requests targeting specific branches you can use the branches: only: key, which will also restrict the branches that trigger builds.

2020-10-11 06:17 UTC, sroy8091 commented
@vfdev-5 now we need to set this variable so that doc will build in actual envs

2020-10-11 21:37 UTC, vfdev-5 commented
@sroy8091 thanks for the update. Looks good.


Following https://github.com/pytorch/ignite/pull/1350#pullrequestreview-501617852
> Could you also add "Nice to have" features ?

How about this ?

2020-10-20 03:23 UTC, sroy8091 commented
@vfdev-5 can you check why i am getting pytest error in travis build?

2020-10-20 09:05 UTC, vfdev-5 reviewed
@sroy8091 thanks for the update. I left few comments on that.

2020-10-20 09:05 UTC, vfdev-5 commented on .travis.yml
> +        - chmod +x .travis/install_docs.sh
Typo as no `install_docs.sh`, right ?

2020-10-20 09:05 UTC, vfdev-5 commented on .travis.yml
> -      install:
Let's keep the same step:
```
install:
    - chmod +x .travis/install_docs.sh
    - ./.travis/install_docs_deps.sh
```
and 
```
script:
  - ...
  - ...
```

2020-10-20 09:05 UTC, vfdev-5 commented on .travis/install_deps.sh
> +source activate test-environment
`source` wont work externally, so when you call pytest etc conda env is not activated.
I propose to change that and install everything in `base` conda env. Thus, we do not have to create/activate another env.

2020-10-20 09:05 UTC, vfdev-5 commented on .travis.yml
> +  - pip install pytest-cov
normally, this is not required.

2020-10-23 08:44 UTC, vfdev-5 requested changes
@sroy8091 thanks for updating the PR, but it still does not look correct.

2020-10-23 08:44 UTC, vfdev-5 commented on .travis.yml
> +  - ./.travis/install_deps.sh
Can you try using `sh .travis/install_deps.sh` instead of 2 lines?

2020-10-23 08:44 UTC, vfdev-5 commented on .travis.yml
> +        - ./.travis/install_docs_deps.sh
Same here and below

2020-10-23 08:44 UTC, vfdev-5 commented on .travis/install_deps.sh
> +conda install torchvision
This line is incorrect.

Let's remove all the lines 11 - 13 and instead put :
```
conda install torchvision cpuonly python=$TRAVIS_PYTHON_VERSION -c $PYTORCH_CHANNEL
```

2020-10-23 08:44 UTC, vfdev-5 commented on .travis.yml
> +#      if: type != cron and $TRAVIS_PULL_REQUEST = True
This should be uncommented, right ? And the condition probably wont work neither, please see the docs : https://docs.travis-ci.com/user/conditions-v1#integration

2020-10-23 09:13 UTC, sroy8091 commented
Yeah, still working on it. The error in build is related to pytest. Is there any way to test this locally?

2020-10-23 09:20 UTC, vfdev-5 commented
>  The error in build is related to pytest. Is there any way to test this locally?

@sroy8091 if you have a docker you can try to run step by step CI intructions in ubuntu:18.04 container. This should be rather close to what it is in travis, except all env vars like `TRAVIS_*`.

2020-12-03 09:44 UTC, vfdev-5 commented
Closed in favor of #1457

2020-12-03 09:44 UTC, closed without merging