Activate MyPy in ignite.contrib.engines
pytorch/ignite pull request #1416
Opened 2020-10-28 16:10 UTC by rzats

Fixes _a subset of_ #1406

Description:

Makes the `ignite.contrib.engines` submodule MyPy-compliant.

Check list:
* [ ] New tests are added (if a new feature is added)
* [ ] New doc strings: description and/or example code are in RST format
* [ ] Documentation is updated (if required)

2020-10-28 16:30 UTC, vfdev-5 commented
@gruebel could you please review this PR ?

2020-10-28 17:55 UTC, gruebel commented
Sure, I will take a look today.

2020-10-28 20:35 UTC, vfdev-5 commented
@rzats thanks for the PR ! Currently, we have to recover mypy testing runs, now on GitHub Actions, due to partial out of service by Travis. Once it is done we could rerun your PR.

2020-10-28 21:15 UTC, gruebel requested changes

2020-10-28 21:15 UTC, gruebel commented on ignite/contrib/engines/common.py
> +    evaluators: Union[Engine, Dict[str, Engine], None],
we usually use `Optional[Union[...]]` instead of adding `None` inside the `Union` part. Please see my comment below for the corrected signature.

2020-10-28 21:15 UTC, gruebel commented on ignite/contrib/engines/common.py
> +        cast(Dict[str, torch.nn.Module], to_save),
No need to use `cast` here, you can adjust the code
https://github.com/pytorch/ignite/blob/92455594401681bbd3e675a664072b905401274b/ignite/contrib/engines/common.py#L596-L598
to
```python
    if isinstance(models, nn.Module):
        to_save = {"model": models}  # type: Dict[str, nn.Module]
    else:
        to_save = models
```

2020-10-28 21:24 UTC, gruebel commented
@rzats  Could you also add missing return types in `common.py` and `tbptt.py`? Would be a great help for making `mypy` checking more strict in the near future 💪

2020-10-29 07:26 UTC, rzats commented
@gruebel thanks for your comments! I've pushed the requested fixes.

2020-10-29 09:55 UTC, vfdev-5 reviewed
@rzats Thanks for the update ! Looks good to me.
@gruebel what do you think ?

2020-10-29 21:28 UTC, gruebel commented
@rzats thanks, looks good!
@vfdev-5 the only thing I would need an opinion from you is about the `ProgressBar.attach()` method. Should we just ignore the incompatible type
https://github.com/pytorch/ignite/blob/1926f2ec999c4e8337d5eec89370be31857093cc/ignite/contrib/engines/common.py#L218-L222
or extend it?
https://github.com/pytorch/ignite/blob/1926f2ec999c4e8337d5eec89370be31857093cc/ignite/contrib/handlers/tqdm_logger.py#L157-L164
`event_name: Events = Events.ITERATION_COMPLETED` -> `event_name: Union[CallableEventWithFilter, Events] = Events.ITERATION_COMPLETED`

2020-10-29 23:56 UTC, vfdev-5 commented
> the only thing I would need an opinion from you is about the ProgressBar.attach() method. Should we just ignore the incompatible type

@gruebel you are right, I'd say we have to extend `ProgressBar.attach` to what you suggest:

> event_name: Events = Events.ITERATION_COMPLETED -> event_name: Union[CallableEventWithFilter, Events] = Events.ITERATION_COMPLETED

2020-10-30 10:09 UTC, gruebel commented
@rzats can you extend the type hint in `ignite/ignite/contrib/handlers/tqdm_logger.py` as mentioned above? After that this PR is good to go!

2020-11-06 14:02 UTC, vfdev-5 commented
@rzats could you please update the PR

2020-11-11 22:21 UTC, rzats commented
@vfdev-5 I've updated this PR (and fixed some additional strict errors that were enabled recently)

2020-11-11 22:50 UTC, vfdev-5 approved these changes
Thanks @rzats ! LGTM

2020-11-11 22:50 UTC, merged