Activate mypy ignite contrib metrics
pytorch/ignite pull request #1419
Opened 2020-10-28 20:09 UTC by zhxxn

Relates to #1406 

Description:
Activate mypy in `ignite.contrib.metrics`

2020-10-28 20:33 UTC, vfdev-5 commented
@zhxxn thanks a lot for the PR ! I'll review it asap. We have to recover mypy testing runs, now on GitHub Actions, due to partial out of service by Travis. Once it is done we could rerun your PR.

2020-10-28 21:39 UTC, gruebel requested changes

2020-10-28 21:39 UTC, gruebel commented on ignite/contrib/metrics/gpu_info.py
> +    def compute(self) -> List:
Could be here a bit more precise and change it to
```python
def compute(self) -> List[Dict[str, Any]]:
```

2020-10-28 21:39 UTC, gruebel commented on ignite/contrib/metrics/gpu_info.py
> +    # TODO: see issue https://github.com/pytorch/ignite/issues/1405
Thanks for adding the reference here 👍

2020-10-28 21:43 UTC, gruebel commented
And could you please add missing return types in `regression.fractional_absolute_error.py`, `regression.fractional_bias.py` and `regression.canberra_metric.py`, thanks 👍

2020-10-28 23:24 UTC, vfdev-5 reviewed
@zhxxn look good ! Thanks. 
Nits: few other suggestion

2020-10-28 23:24 UTC, vfdev-5 commented on ignite/contrib/metrics/regression/geometric_mean_absolute_error.py
>                  "GeometricMeanAbsoluteError must have at " "least one example before it can be computed."
```suggestion
                "GeometricMeanAbsoluteError must have at least one example before it can be computed."
```

2020-10-28 23:24 UTC, vfdev-5 commented on ignite/contrib/metrics/regression/geometric_mean_relative_absolute_error.py
>                  "GeometricMeanRelativeAbsoluteError must have at least " "one example before it can be computed."
```suggestion
                "GeometricMeanRelativeAbsoluteError must have at least one example before it can be computed."
```

2020-10-31 10:02 UTC, gruebel commented
LGTM 👍

2020-10-31 12:08 UTC, vfdev-5 approved these changes
Thanks a lot for the PR @zhxxn !

2020-10-31 12:09 UTC, merged