Update rmse, ssim, top_k_categorical_accuracy in test for generating data with different rank
pytorch/ignite pull request #2673
Opened 2022-08-24 08:50 UTC by puhuk

Description: Update `rmse`, `ssim`, `top_k_categorical_accuracy`

Check list:

- [x] New tests are added (if a new feature is added)
- [ ] New doc strings: description and/or example code are in RST format
- [ ] Documentation is updated (if required)

2022-08-26 07:17 UTC, sadra-barikbin requested changes

2022-08-26 07:17 UTC, sadra-barikbin commented on tests/ignite/metrics/test_top_k_categorical_accuracy.py
> +        offset = n_iters * batch_size
Here as well.

2022-08-26 07:22 UTC, sadra-barikbin commented on tests/ignite/metrics/test_top_k_categorical_accuracy.py
> +        offset = n_iters * batch_size
May be you've forgotten to add `rank` to `manual_seed` call in line 62

2022-08-26 07:46 UTC, sadra-barikbin commented on tests/ignite/metrics/test_ssim.py
> +    offset = n_iters * batch_size
Maybe you've forgotten to call `torch.manual_seed(12 + rank)`.

2022-08-26 12:40 UTC, sadra-barikbin commented on tests/ignite/metrics/test_top_k_categorical_accuracy.py
> +    for i in range(3):
So you could bring line 61 near here.

2022-08-27 15:55 UTC, sadra-barikbin commented on tests/ignite/metrics/test_top_k_categorical_accuracy.py
> +    for i in range(3):
Could you please put it outside the `for` loop?

2022-08-29 06:52 UTC, sadra-barikbin approved these changes

2022-09-01 15:28 UTC, vfdev-5 commented on tests/ignite/metrics/test_ssim.py
> +                y[i * batch_size : (i + 1) * batch_size],
```suggestion
                y_pred[i * batch_size : (i + 1) * batch_size, ...],
                y[i * batch_size : (i + 1) * batch_size, ...],
```

2022-09-01 15:29 UTC, vfdev-5 commented on tests/ignite/metrics/test_top_k_categorical_accuracy.py
> +                y_true[i * batch_size : (i + 1) * batch_size, :],
```suggestion
                y_true[i * batch_size : (i + 1) * batch_size],
```

2022-09-01 15:29 UTC, vfdev-5 approved these changes

2022-09-02 21:35 UTC, merged